#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

VERSION='2.0.0'

wgetex() {
	args=("$@")
	if [[ "${ANONFILESDL_USER_AGENT-a}" == "${ANONFILESDL_USER_AGENT-b}" ]]; then
		args=('-U' "${ANONFILESDL_USER_AGENT}" "${args[@]}")
	fi
	if [[ "${ANONFILESDL_NO_CHECK_CERTIFICATE-0}" == 1 ]]; then
		args=('--no-check-certificate' "${args[@]}")
	elif [[ -n "${ANONFILESDL_CA_CERTIFICATE-}" ]]; then
		args=("--ca-certificate=${ANONFILESDL_CA_CERTIFICATE}" "${args[@]}")
	fi
	wget "${args[@]}"
}

download() {
	local url="$1"
	local html="$(wgetex -qO- "${url}")"
	local html_button="$(grep 'download-url' -A 4 <<< "${html}")"
	local html_button_href="$(grep -o 'href=".*"' <<< "${html_button}")"
	local download_url="$(cut -d'"' -f2 <<< "${html_button_href}")"
	wgetex -S -c "${download_url}"
}

usage() {
	echo "Usage: $(basename "$0") [options...] <url>"
	echo " -h, --help          Show help"
	echo " -V, --version       Show version"
	echo
	echo "Env:"
	echo " ANONFILESDL_USER_AGENT=<string>        User agent string"
	echo " ANONFILESDL_CA_CERTIFICATE=<file>      CA cert bundle"
	echo " ANONFILESDL_NO_CHECK_CERTIFICATE=<0|1> Do not validate the server cert"
}

if [[ "$#" -lt 1 ]]; then
	usage >&2
	exit 1
fi

if [[ "$1" == '-V' || "$1" == '--version' ]]; then
	echo "${VERSION}"
	exit 0
fi

if [[ "$1" == '-h' || "$1" == '--help' ]]; then
	usage
	exit 0
fi

url="$1"
download "${url}"
