#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

VERSION='1.0.0'

wgetua() {
	local ua_a="${ANONFILESDL_USER_AGENT-a}"
	local ua_b="${ANONFILESDL_USER_AGENT-b}"
	if [[ "${ua_a}" == "${ua_b}" ]]; then
		wget -U "${ua_a}" "$@"
	else
		wget "$@"
	fi
}

download() {
	local url="$1"
	local html="$(wget -qO- "$url")"
	local html_button="$(grep 'download-url' -A 4 <<< "$html")"
	local html_button_href="$(grep -o 'href=".*"' <<< "$html_button")"
	local download_url="$(cut -d'"' -f2 <<< "$html_button_href")"
	wget -S -c "${download_url}"
}

usage() {
	echo "Usage: $(basename "$0") [options...] <url>"
	echo " -h, --help          Show help"
	echo " -V, --version       Show version"
}

if [[ "$#" -lt 1 ]]; then
	usage >&2
	exit 1
fi

if [[ "$1" == '-V' || "$1" == '--version' ]]; then
	echo "$VERSION"
	exit 0
fi

if [[ "$1" == '-h' || "$1" == '--help' ]]; then
	usage
	exit 0
fi

url="$1"
ret=0
if [[ "${url}" == '-' ]]; then
	while read -r line; do
		if [[ "${line}" = 'https://'* || "${line}" = 'http://'* ]]; then
			echo "${line}"
			(download "${line}") && true
			if [[ "$?" != 0 ]]; then
				ret=1
			fi
		fi
	done < <(cat 2>/dev/null; echo)
else
	(download "$url") && true
	if [[ "$?" != 0 ]]; then
		ret=1
	fi
fi
exit "${ret}"
